from enum import Enum
class ActionEnum(Enum):
    NO_ACTION = "NO_ACTION"
    RIDING = "RIDING" 
    WAITING = "WAITING"
    ACTION = "ACTION"
    RESTING = "RESTING"
    UNAVAILABLE = "UNAVAILABLE"
    GETOFF = "GETOFF"

    RIDING_BACK_TO_RESTAURANT_AREA = "RIDING_BACK_TO_RESTAURANT_AREA" 