from enum import Enum
class ActionEnum(Enum):
    NO_ACTION = "NO_ACTION"
    RIDING = "RIDING" 
    WAITING = "WAITING"
    PICKUP_OR_DELIVER = "PICKUP_OR_DELIVER"
    RESTING = "RESTING"
    UNAVAILABLE = "UNAVAILABLE"